export const TEMPLATES = [
  {
    id: "coaching-business-entrepreneurs",
    name: "Coaching Business — Entrepreneurs",
    description: "Process de closing en 9 étapes pour vendre un accompagnement business à des entrepreneurs. Qualification approfondie, projection, storytelling et traitement de 7 objections.",
    category: "Business",
    tags: ["Coaching business", "Entrepreneurs", "High ticket", "30 min"],
    author: "Rumos.ai",
    script: {
      name: "Coaching Business — Entrepreneurs",
      goal: "Closer le prospect sur votre accompagnement business",
      duration_minutes: 30,
      reminders: [
        "Le prospect n'en a rien à faire de votre offre — parlez de LUI, ses problèmes, ses rêves",
        "Posez des questions, ne donnez pas de réponses — prospect 80%, vous 20%",
        "Oubliez que vous voulez vendre, commencez à aider",
        "N'ayez pas peur des objections — la vente commence au premier NON",
      ],
      steps: [
        {
          order: 1, name: "Intro et plan d'appel", goal: "Créer la connexion et poser le cadre du call", duration_estimate_minutes: 3,
          key_phrases: ["Tu es dans quelle énergie aujourd'hui ?", "J'ai quelques critères de sélection", "Je ne peux pas prendre plus de X coachés", "Ça va durer 30 min"],
          script_lines: [
            "Salut [Prénom], c'est très cool de pouvoir se parler aujourd'hui !",
            "Alors je t'explique comment va se dérouler ce call : je vais d'abord te poser quelques questions pour bien comprendre tes enjeux et tes objectifs, et ensuite je t'expliquerai comment je peux t'aider.",
            "C'est important que tu comprennes que pour que je sois 100% efficace avec les personnes que j'accompagne, j'ai quelques critères de sélection.",
            "Aussi pour être 100% investi avec mes coachés, je ne peux pas en prendre plus de [X].",
            "Ça va durer 30 min.",
          ],
          questions: ["Tu es dans quelle énergie aujourd'hui ?", "C'est ok pour toi ?"],
          tips: ["Poser le cadre de rareté dès le début pour créer l'autorité", "Obtenir un OUI sur le déroulé avant de commencer"],
        },
        {
          order: 2, name: "Qualification — Découvrir les douleurs", goal: "Comprendre pourquoi il est là, sa situation, ses freins profonds et qui décide", duration_estimate_minutes: 10,
          key_phrases: ["Pourquoi tu as réservé cet échange ?", "C'est quoi ta situation actuelle ?", "Qu'est-ce que tu regardes comme autre programme ?", "Qui prend la décision ?"],
          script_lines: [],
          questions: ["Pourquoi tu as réservé cet échange avec moi ? Pourquoi on est là ?", "Qu'est-ce qui t'a poussé à réserver cet échange ?", "C'est quoi ta situation actuelle ?", "Quels sont tes objectifs ?", "Qu'est-ce que tu as prévu de mettre en place pour y arriver ?", "Quelle source de revenu tu as aujourd'hui ?", "Qu'est-ce que tu regardes comme autre programme pour te faire accompagner ?", "C'est quoi les 2 points forts avec eux ? Les 2 points d'amélioration ?", "Quelles sont tes ambitions ?", "Qu'est-ce qu'il te manque aujourd'hui ?", "Qu'est-ce qui te limite le plus en ce moment ?", "Qui prend la décision ?"],
          tips: ["Identifier le décideur dès cette étape — crucial pour le closing", "Écouter 80% du temps, ne pas pitcher", "Adapter les questions en fonction de la douleur principale identifiée"],
        },
        {
          order: 3, name: "Jauger la motivation", goal: "Mesurer l'urgence, identifier les freins à l'action autonome", duration_estimate_minutes: 3,
          key_phrases: ["Sur une échelle de 0 à 10", "Qu'est-ce qui t'empêche de le faire par toi-même ?"],
          script_lines: [],
          questions: ["Sur une échelle de 0 à 10, à combien tu évalues l'urgence de trouver une solution ?", "Qu'est-ce qui t'empêche de le faire par toi-même ?", "Quand est-ce que tu aimerais commencer ?", "Qu'est-ce que tu es prêt à faire pour atteindre tes objectifs ?"],
          tips: ["Si score < 7, creuser pourquoi — soit sous-exprimé, soit prospect non qualifié", "Garder la réponse au 'par toi-même' pour la réutiliser à l'étape Offre"],
        },
        {
          order: 4, name: "Projeter sur les objectifs", goal: "Cristalliser les objectifs et créer une vision émotionnelle du futur réussi", duration_estimate_minutes: 3,
          key_phrases: ["Quels sont tes objectifs dans 3 mois ?", "Là on est dans 3 mois, tu as atteint ton objectif"],
          script_lines: [],
          questions: ["Quels sont tes objectifs dans 3 mois ? Et dans 6 mois ?", "Quel serait ton objectif idéal ?", "Pourquoi c'est important pour toi d'atteindre ces objectifs ?", "Là on est dans 3 mois, tu as atteint ton objectif principal — qu'est-ce que ça change dans ta vie ?"],
          tips: ["La projection dans 3 mois est une technique de visualisation — laisser le prospect s'exprimer pleinement", "Mémoriser les réponses émotionnelles pour le récapitulatif"],
        },
        {
          order: 5, name: "Récapitulatif et permission pitcher", goal: "Valider les enjeux et obtenir l'accord pour présenter l'offre + la promesse de décision", duration_estimate_minutes: 2,
          key_phrases: ["Si j'ai bien compris tes objectifs", "C'est bien ça ?", "Est-ce que tu me permets de te présenter", "J'aimerais qu'on évite les je vais y réfléchir"],
          script_lines: [
            "Ok donc si j'ai bien compris les objectifs pour toi c'est de : [RECAP OBJECTIFS]",
            "Ok écoute, moi je peux t'aider.",
            "Juste d'abord, ce que je te demande — et c'est important pour moi — j'aimerais qu'une fois que je t'ai présenté l'accompagnement, tu puisses prendre une décision.",
            "Tu pourras me dire oui j'ai envie de me lancer avec toi, ou non j'ai envie de continuer seul.",
            "Je veux juste qu'on évite les 'je vais y réfléchir' ou 'pas maintenant'.",
            "Parce que je suis convaincu qu'un bon entrepreneur, ça doit savoir prendre des décisions rapidement.",
          ],
          questions: ["C'est bien ça ?", "Est-ce que tu me permets de te présenter mon programme d'accompagnement ?", "Est-ce que c'est okay pour toi ?"],
          tips: ["Obtenir DEUX accords : (1) sur le recap, (2) sur la promesse de décision", "La promesse de décision neutralise 'je vais y réfléchir' avant qu'elle arrive", "Ne pas pitcher sans ces deux accords"],
        },
        {
          order: 6, name: "Présentation de l'offre", goal: "Pitcher le programme avec storytelling, contenu et bénéfices", duration_estimate_minutes: 5,
          key_phrases: ["[Nom de votre programme]", "[durée de l'accompagnement]", "Sur une échelle de 0 à 10, à combien tu es chaud ?"],
          script_lines: [
            "Le but c'est que le travail qu'on va faire ensemble te permette d'atteindre tes objectifs et te mettre en mouvement le plus rapidement possible.",
            "[STORYTELLING] Pourquoi j'ai créé ce programme : [votre histoire, vos résultats, votre légitimité].",
            "[NOM DU PROGRAMME], ça dure [durée]. C'est un accompagnement pragmatique qui comprend : [lister les grandes parties de votre méthode].",
            "Pendant [durée] : [lister les modalités : sessions 1-1, groupe, canal direct, accès communauté, etc.].",
            "Ce que je vais t'apporter : un effet miroir pour te challenger, tu me rendras des comptes, je serai ton soutien dans les moments durs.",
            "Mon but c'est vraiment de te bouger — tes résultats vont dépendre de ton implication.",
          ],
          questions: ["Okay ça va jusqu'ici ?", "As-tu des questions sur des points en particulier ?", "Sur une échelle de 0 à 10, à combien tu es chaud pour rejoindre le programme ?", "Qu'est-ce qui te manque pour aller à 9 ou 10 ?"],
          tips: ["Storytelling avant programme — créer la crédibilité avant de pitcher", "Vérifier la compréhension après chaque grande partie", "Le score 0-10 après le pitch révèle les objections cachées"],
        },
        {
          order: 7, name: "Éligibilité", goal: "Retourner la dynamique — c'est vous qui choisissez, pas lui", duration_estimate_minutes: 2,
          key_phrases: ["J'ai 3 critères", "As-tu la capacité de te faire coacher ?", "Tu m'as donné envie de te prendre en coaching"],
          script_lines: [
            "Pour être sûr que tu corresponds bien à cet accompagnement, j'ai 3 critères et j'ai besoin de savoir si tu y réponds.",
            "Critère numéro 1 : as-tu la capacité de te faire coacher ?",
            "Critère numéro 2 : as-tu une vraie ambition sur ce projet ?",
            "Critère numéro 3 : as-tu la capacité de prendre des décisions ?",
            "Là tu m'as donné envie de te prendre en coaching, alors on va le faire.",
          ],
          questions: [],
          tips: ["Les 3 critères sont rhétoriques — tout bon prospect dira oui", "L'inversion 'tu m'as donné envie' renverse le rapport de force", "Enchaîner directement sur le prix sans pause"],
        },
        {
          order: 8, name: "Prix", goal: "Annoncer le prix clairement et ancrer la valeur", duration_estimate_minutes: 2,
          key_phrases: ["[votre prix]", "[découpage mensuel]", "un investissement"],
          script_lines: [
            "Pour avoir accès à [NOM DU PROGRAMME], ça représente un investissement de [PRIX] pour [DURÉE], soit [PRIX/MOIS] par mois.",
            "Et pour rappel ça comprend : [récapituler tous les éléments inclus dans l'offre].",
          ],
          questions: [],
          tips: ["Annoncer le prix sans hésitation ni excuses", "Récapituler ce qui est inclus pour ancrer la valeur", "Se taire après avoir annoncé le prix — le premier qui parle perd"],
        },
        {
          order: 9, name: "Closing", goal: "Obtenir le OUI et lancer le paiement immédiatement", duration_estimate_minutes: 2,
          key_phrases: ["On part là-dessus ?", "Je t'envoie un lien de paiement", "Des zones d'ombre ?"],
          script_lines: [
            "→ SE TAIRE après la question. Le premier qui parle perd.",
            "Okay donc voilà comment ça se passe : je t'envoie un lien de validation et de paiement et on valide ça ensemble maintenant.",
            "Je t'ajoute à [vos espaces/outils de suivi].",
            "On fixe ensemble notre première session dans l'agenda.",
          ],
          questions: ["Est-ce que c'est clair pour toi, on part là-dessus ?", "Est-ce qu'il y a encore des zones d'ombre que tu aimerais qu'on éclaircisse ?"],
          tips: ["RÈGLE D'OR : se taire après 'on part là-dessus ?' — le premier qui parle perd", "Enchaîner sur les next steps immédiatement après le OUI pour éviter le retour arrière"],
        },
      ],
      objections: [
        { order: 1, label: "C'est trop cher", category: "price", trigger_phrases: ["c'est cher", "c'est trop cher", "c'est beaucoup", "le prix", "c'est élevé"], applicable_step_orders: [8, 9], responses: ["Je comprends que ça puisse être un prix important — c'est parce que c'est une offre importante.", "Est-ce que c'est trop cher parce que tu n'as pas le budget, ou parce que tu penses que ça ne vaut pas ce prix ?", "Si je t'offrais ce service gratuitement, le prendrais-tu ?", "Si tu atteins tes objectifs, tu trouveras ça toujours trop cher ?", "Ce que je te propose aujourd'hui, ce n'est pas une dépense — c'est un investissement."], key_reframe: "Dépense vs investissement — faire calculer mentalement le ROI si les objectifs sont atteints" },
        { order: 2, label: "Je n'ai pas le budget", category: "budget", trigger_phrases: ["j'ai pas l'argent", "pas de budget", "je n'ai pas les moyens", "financièrement c'est compliqué"], applicable_step_orders: [8, 9], responses: ["À part le problème du budget, tout est bon — on pourrait commencer si il n'y avait pas ça ?", "Est-ce une question logistique ou une part trop importante de ton budget ?", "Si on pouvait faire un paiement en 2 ou 3 fois, est-ce que tu serais d'accord ?"], key_reframe: "Isoler le budget comme seul frein, puis proposer un échelonnement" },
        { order: 3, label: "Je vais y réfléchir", category: "stall", trigger_phrases: ["je vais y réfléchir", "j'ai besoin de temps", "laisse-moi réfléchir", "je reviens vers toi"], applicable_step_orders: [8, 9], responses: ["Je comprends — à quoi dois-tu réfléchir simplement ?", "Y a-t-il un sujet qu'on n'a pas abordé durant l'appel ?", "Qu'est-ce qui te bloque pour passer à l'action maintenant ?", "Ta décision est liée aux informations que tu as — je suis là maintenant."], key_reframe: "La réflexion n'est jamais une question de temps — c'est une question d'informations manquantes" },
        { order: 4, label: "Ce n'est pas le bon moment", category: "timing", trigger_phrases: ["c'est pas le bon moment", "pas maintenant", "plus tard", "dans quelques mois"], applicable_step_orders: [8, 9], responses: ["Qu'est-ce qu'il nous manque pour commencer dès maintenant ?", "Tu n'auras pas évolué entre maintenant et dans 3 mois sans action.", "Ce n'est pas une question de temps, c'est une question d'informations."], key_reframe: "Le 'bon moment' n'existe pas — la situation ne changera pas sans action" },
        { order: 5, label: "Je parle aussi avec vos concurrents", category: "competition", trigger_phrases: ["je regarde d'autres options", "j'ai parlé avec", "je compare", "j'ai une autre proposition"], applicable_step_orders: [2, 8, 9], responses: ["Mes concurrents sont très bons. Mais si tu leur as déjà parlé, qu'est-ce qui te retient de travailler avec eux ?", "Qu'est-ce qui t'a amené à réserver cet appel avec moi aussi ?"], key_reframe: "Amener le prospect à ses propres conclusions — ne jamais dénigrer les concurrents" },
        { order: 6, label: "Est-ce que ça va vraiment marcher pour moi ?", category: "doubt", trigger_phrases: ["est-ce que ça marche vraiment", "j'ai des doutes", "comment tu peux garantir", "et si ça ne fonctionne pas"], applicable_step_orders: [6, 7, 8, 9], responses: ["La seule chose que je peux garantir : si tu ne fais rien, tu conserveras ton problème.", "Il m'est impossible de garantir 100% — ça dépend aussi de ton implication.", "Rappelle-toi tes objectifs — est-ce que tu veux que dans 3 mois rien n'ait changé ?"], key_reframe: "L'inaction est la seule certitude de ne pas réussir" },
        { order: 7, label: "Je dois en parler avec mon associé / ma femme", category: "third_party", trigger_phrases: ["j'en parle à ma femme", "j'en parle à mon mari", "mon associé", "on décide ensemble"], applicable_step_orders: [8, 9], responses: ["Est-ce que tu penses que ton/ta partenaire va te soutenir dans cette démarche ?", "Pourquoi tu as besoin de lui/elle demander son avis ?", "Est-ce qu'il/elle sait que tu as les problèmes dont on a parlé ?"], key_reframe: "Ne pas avoir résolu le problème est aussi une décision que le partenaire n'approuve pas" },
      ],
    },
  },
  {
    id: "coaching-finances-personnelles",
    name: "Coaching Finances Personnelles",
    description: "Process de closing pour vendre un accompagnement en gestion des finances personnelles. Qualification de la situation financière, projection sur les objectifs d'épargne et traitement de 6 objections.",
    category: "Finances",
    tags: ["Coaching finances", "B2C", "Finances perso", "30 min"],
    author: "Rumos.ai",
    script: {
      name: "Coaching Finances Personnelles",
      goal: "Closer le prospect sur votre accompagnement en gestion des finances personnelles",
      duration_minutes: 30,
      reminders: [
        "L'argent est un sujet sensible — écoute sans juger, mets à l'aise dès le début",
        "Le prospect sait que quelque chose ne va pas — ton rôle c'est de lui montrer qu'il peut en sortir",
        "Ne parle pas de chiffres avant d'avoir compris sa situation émotionnelle avec l'argent",
        "La honte est souvent le vrai frein — normalise sa situation avant de proposer une solution",
      ],
      steps: [
        {
          order: 1, name: "Intro et plan d'appel", goal: "Mettre à l'aise et poser un cadre bienveillant", duration_estimate_minutes: 3,
          key_phrases: ["Cet appel est un espace safe", "Pas de jugement", "Je t'explique comment ça va se passer"],
          script_lines: [
            "Salut [Prénom], merci d'avoir pris le temps de réserver cet appel.",
            "Avant tout, je veux que tu saches que cet échange est un espace safe — ce que tu me dis reste entre nous, et il n'y a aucun jugement de ma part.",
            "Voilà comment ça va se passer : je vais d'abord te poser quelques questions pour bien comprendre ta situation et tes objectifs, et ensuite je t'expliquerai comment je peux t'aider.",
            "Ça va durer environ 30 minutes.",
          ],
          questions: ["Comment tu vas aujourd'hui ?", "C'est ok pour toi qu'on passe 30 minutes ensemble ?"],
          tips: ["Insister sur la bienveillance — les finances perso génèrent souvent de la honte", "Créer un espace sécurisant avant toute question"],
        },
        {
          order: 2, name: "Qualification — Situation financière actuelle", goal: "Comprendre la situation, les habitudes et les douleurs financières", duration_estimate_minutes: 10,
          key_phrases: ["C'est quoi ta relation à l'argent ?", "Tu sais combien tu dépenses chaque mois ?", "Tu as une épargne ?", "Tu as des dettes ?"],
          script_lines: [],
          questions: [
            "Qu'est-ce qui t'a amené à réserver cet appel aujourd'hui ?",
            "Comment tu décrirais ta relation à l'argent en ce moment ?",
            "Est-ce que tu sais précisément combien tu gagnes et combien tu dépenses chaque mois ?",
            "Tu as une épargne ? Si oui, elle représente combien de mois de dépenses ?",
            "Tu as des crédits ou des dettes en cours ?",
            "Est-ce que tu te retrouves souvent à court d'argent avant la fin du mois ?",
            "Quand tu penses à tes finances, c'est quoi l'émotion principale — stress, honte, confusion ?",
            "C'est quoi la décision financière que tu regrettes le plus ?",
            "Tu as déjà essayé de mettre en place un budget ? Qu'est-ce qui n'a pas marché ?",
            "Qui prend les décisions financières chez toi ?",
          ],
          tips: ["Ne pas réagir avec surprise ou jugement face aux chiffres annoncés", "Reformuler avec empathie : 'Je comprends, c'est une situation que beaucoup de gens vivent'", "Identifier le déclencheur émotionnel qui a poussé à réserver l'appel"],
        },
        {
          order: 3, name: "Jauger la motivation", goal: "Mesurer l'urgence et identifier ce qui bloque l'action autonome", duration_estimate_minutes: 3,
          key_phrases: ["Sur une échelle de 0 à 10", "Qu'est-ce qui t'empêche de le faire seul ?"],
          script_lines: [],
          questions: [
            "Sur une échelle de 0 à 10, à combien tu évalues l'urgence de reprendre le contrôle de tes finances ?",
            "Qu'est-ce qui t'a empêché de t'y mettre jusqu'ici ?",
            "Si tu ne fais rien dans les 6 prochains mois, tu imagines ta situation comment ?",
            "Qu'est-ce que tu es prêt à changer dans tes habitudes pour y arriver ?",
          ],
          tips: ["Si score < 7, creuser : est-ce un manque d'urgence ou de la résignation ?", "La résignation ('ça n'a jamais marché') est une objection à traiter dès maintenant"],
        },
        {
          order: 4, name: "Projeter sur les objectifs", goal: "Créer une vision concrète et émotionnelle d'une vie financière saine", duration_estimate_minutes: 3,
          key_phrases: ["Dans 6 mois tu as atteint ton objectif", "Qu'est-ce que ça change dans ta vie ?", "C'est quoi ton objectif idéal"],
          script_lines: [],
          questions: [
            "C'est quoi ton objectif financier principal dans les 6 prochains mois ?",
            "Si tu avais une épargne de sécurité, ça changerait quoi dans ton quotidien ?",
            "Dans 6 mois tu as atteint ton objectif — qu'est-ce que tu ressens ?",
            "C'est quoi la première chose que tu ferais si tu n'avais plus de stress financier ?",
          ],
          tips: ["Laisser le prospect verbaliser l'émotion — ne pas la deviner à sa place", "Mémoriser les réponses pour le récapitulatif"],
        },
        {
          order: 5, name: "Récapitulatif et permission pitcher", goal: "Valider les enjeux et obtenir l'accord pour présenter l'accompagnement", duration_estimate_minutes: 2,
          key_phrases: ["Si j'ai bien compris", "C'est bien ça ?", "Est-ce que tu me permets de te présenter", "une décision dans un sens ou dans l'autre"],
          script_lines: [
            "Ok donc si j'ai bien compris, en ce moment tu vis [RECAP SITUATION] et ton objectif c'est [RECAP OBJECTIF].",
            "Et ce qui t'empêche d'y arriver seul c'est [RECAP FREIN].",
            "Je peux t'aider à changer ça.",
            "Avant que je te présente comment, j'ai juste besoin que tu t'engages à prendre une décision après cet appel — oui on avance ensemble, ou non tu continues seul.",
            "Pas de 'je vais y réfléchir' — tu as déjà toutes les infos pour décider.",
          ],
          questions: ["C'est bien ça ?", "Est-ce que tu me permets de te présenter mon accompagnement ?"],
          tips: ["Reformuler avec les mots exacts du prospect — ça montre que tu as vraiment écouté", "Obtenir les deux accords avant de pitcher"],
        },
        {
          order: 6, name: "Présentation de l'offre", goal: "Présenter le programme avec méthode, livrables et résultats attendus", duration_estimate_minutes: 5,
          key_phrases: ["[Nom du programme]", "[durée]", "Sur une échelle de 0 à 10, à combien tu es partant ?"],
          script_lines: [
            "[STORYTELLING] Pourquoi j'ai créé cet accompagnement : [votre histoire, votre légitimité, vos résultats].",
            "Mon programme [NOM DU PROGRAMME] dure [DURÉE]. Concrètement on va travailler sur : [lister les axes : budget, épargne, dettes, investissement, etc.].",
            "Pendant [DURÉE] tu auras accès à : [lister les modalités : sessions 1-1, outils, suivi, etc.].",
            "À la fin, tu sauras exactement où va ton argent, tu auras une épargne active, et tu n'auras plus de stress financier en fin de mois.",
          ],
          questions: ["Ça te parle ?", "Est-ce que tu as des questions ?", "Sur une échelle de 0 à 10, à combien tu es partant pour démarrer ?", "Qu'est-ce qui te manque pour aller à 9 ou 10 ?"],
          tips: ["Utiliser des exemples concrets de résultats (avec ou sans chiffres précis)", "Le score 0-10 révèle les objections cachées — creuser immédiatement"],
        },
        {
          order: 7, name: "Éligibilité", goal: "Retourner la dynamique — c'est vous qui choisissez", duration_estimate_minutes: 2,
          key_phrases: ["J'ai 3 critères", "Es-tu prêt à changer tes habitudes ?", "Tu m'as donné envie de t'accompagner"],
          script_lines: [
            "Pour être sûr que tu correspondes bien à cet accompagnement, j'ai 3 critères.",
            "Critère 1 : es-tu prêt à regarder honnêtement ta situation financière, même si c'est inconfortable ?",
            "Critère 2 : es-tu prêt à changer certaines habitudes ?",
            "Critère 3 : es-tu prêt à prendre des décisions et à les tenir ?",
            "Tu m'as donné envie de t'accompagner. On y va.",
          ],
          questions: [],
          tips: ["Les 3 critères sont rhétoriques mais créent un engagement moral", "L'inversion renverse le rapport de force"],
        },
        {
          order: 8, name: "Prix", goal: "Annoncer le prix clairement et ancrer la valeur", duration_estimate_minutes: 2,
          key_phrases: ["[votre prix]", "un investissement", "ce que ça te coûte de ne rien faire"],
          script_lines: [
            "Pour avoir accès à [NOM DU PROGRAMME], c'est un investissement de [PRIX] pour [DURÉE].",
            "Et pour rappel, ça comprend : [récapituler les livrables].",
            "Pose-toi la question : combien te coûte de continuer comme ça — en stress, en mauvaises décisions, en argent gaspillé ?",
          ],
          questions: [],
          tips: ["Annoncer le prix sans excuses", "L'argument du 'coût de l'inaction' est particulièrement fort dans les finances perso", "Se taire après le prix"],
        },
        {
          order: 9, name: "Closing", goal: "Obtenir le OUI et lancer le démarrage immédiatement", duration_estimate_minutes: 2,
          key_phrases: ["On part là-dessus ?", "Je t'envoie le lien", "Des zones d'ombre ?"],
          script_lines: [
            "→ SE TAIRE après la question. Le premier qui parle perd.",
            "Voilà comment ça se passe : je t'envoie le lien de paiement, on valide ensemble maintenant.",
            "Je t'envoie l'accès à [vos outils/espace de travail].",
            "On fixe notre première session dans l'agenda.",
          ],
          questions: ["On part là-dessus ?", "Il y a encore des zones d'ombre qu'on n'a pas éclaircies ?"],
          tips: ["RÈGLE D'OR : silence après 'on part là-dessus ?'", "Enchaîner sur les next steps immédiatement après le OUI"],
        },
      ],
      objections: [
        { order: 1, label: "C'est trop cher", category: "price", trigger_phrases: ["c'est cher", "c'est trop cher", "le prix", "c'est beaucoup d'argent"], applicable_step_orders: [8, 9], responses: ["Je comprends — et c'est justement parce que tu gères serré que c'est difficile.", "Mais pose-toi la question : combien tu perds chaque mois à cause de mauvaises habitudes financières ?", "Ce n'est pas une dépense — c'est l'investissement qui va te permettre d'en faire d'autres.", "Si tu atteins tes objectifs, tu trouveras encore ça trop cher ?"], key_reframe: "Le coût de l'accompagnement vs le coût de l'inaction sur 12 mois" },
        { order: 2, label: "Je n'ai pas le budget", category: "budget", trigger_phrases: ["j'ai pas l'argent", "pas de budget", "je n'ai pas les moyens"], applicable_step_orders: [8, 9], responses: ["À part le budget, tout est bon — si on trouvait une solution de paiement, tu serais prêt ?", "On peut regarder ensemble un étalement en 2 ou 3 fois.", "Tu n'as pas les moyens de payer l'accompagnement, ou tu n'as pas les moyens de continuer comme ça ?"], key_reframe: "Isoler le budget comme seul frein et proposer un étalement" },
        { order: 3, label: "Je peux me débrouiller seul avec des livres / YouTube", category: "doubt", trigger_phrases: ["je vais regarder sur YouTube", "j'ai des livres", "je vais me former seul", "il y a plein de ressources gratuites"], applicable_step_orders: [6, 8, 9], responses: ["Tu as probablement déjà accès à ces ressources depuis un moment — qu'est-ce qui s'est passé ?", "La différence entre l'information et l'accompagnement, c'est l'exécution et la responsabilité.", "Ce n'est pas un manque de savoir qui t'a amené ici — c'est un manque de passage à l'action."], key_reframe: "Le problème n'est pas l'accès à l'information — c'est l'implémentation et la régularité" },
        { order: 4, label: "Je vais y réfléchir", category: "stall", trigger_phrases: ["je vais y réfléchir", "laisse-moi réfléchir", "je reviens vers toi"], applicable_step_orders: [8, 9], responses: ["À quoi dois-tu réfléchir exactement ?", "Y a-t-il une information que tu n'as pas et qui t'aiderait à décider ?", "Dans 3 mois, ta situation financière aura changé seul ?"], key_reframe: "La réflexion n'est jamais une question de temps — c'est une information manquante" },
        { order: 5, label: "Ce n'est pas le bon moment", category: "timing", trigger_phrases: ["c'est pas le bon moment", "après les vacances", "en janvier", "quand j'aurai plus de stabilité"], applicable_step_orders: [8, 9], responses: ["Quand est-ce que ce sera le bon moment — qu'est-ce qui doit changer d'ici là ?", "Le bon moment pour reprendre le contrôle de ses finances, c'est toujours maintenant.", "Attendre ne changera pas ta situation — au contraire."], key_reframe: "Il n'y a pas de 'bon moment' pour gérer ses finances — chaque mois d'attente a un coût" },
        { order: 6, label: "Je dois en parler avec mon conjoint", category: "third_party", trigger_phrases: ["j'en parle à ma femme", "j'en parle à mon mari", "mon conjoint doit être au courant", "on gère l'argent ensemble"], applicable_step_orders: [8, 9], responses: ["Est-ce que ton/ta conjoint(e) est au courant de la situation dont on a parlé ?", "Tu penses qu'il/elle va te soutenir dans cette démarche ?", "Si vous gérez l'argent ensemble, ce serait encore plus puissant de faire ça en couple — est-ce qu'on peut l'inclure dans l'accompagnement ?"], key_reframe: "Transformer le tiers en allié potentiel plutôt qu'en obstacle" },
      ],
    },
  },
  {
    id: "coaching-running-objectifs",
    name: "Coaching Running & Objectifs Sportifs",
    description: "Process de closing pour vendre un accompagnement running ou sportif. De la qualification du niveau actuel jusqu'au closing, avec projection sur l'objectif course et traitement de 6 objections.",
    category: "Sport",
    tags: ["Coaching sportif", "Running", "B2C", "Objectifs", "30 min"],
    author: "Rumos.ai",
    script: {
      name: "Coaching Running & Objectifs Sportifs",
      goal: "Closer le prospect sur votre accompagnement running/sportif",
      duration_minutes: 30,
      reminders: [
        "Le prospect a souvent essayé seul et échoué — valorise son courage d'avoir réessayé",
        "L'objectif de course est souvent symbolique (fierté, santé, dépassement de soi) — creuse le pourquoi",
        "Ne parle pas de programme ou d'entraînement avant d'avoir compris sa motivation profonde",
        "La peur de se blesser et le manque de temps sont les deux vrais freins à anticiper",
      ],
      steps: [
        {
          order: 1, name: "Intro et plan d'appel", goal: "Créer la connexion et poser le cadre", duration_estimate_minutes: 3,
          key_phrases: ["Tu es dans quelle énergie aujourd'hui ?", "Je vais te poser quelques questions", "Ça va durer 30 min"],
          script_lines: [
            "Salut [Prénom], content(e) qu'on ait pu caler cet appel !",
            "Voilà comment ça va se passer : je vais d'abord te poser quelques questions pour bien comprendre ton niveau, tes objectifs et tes contraintes, et ensuite je t'expliquerai comment mon accompagnement peut t'aider.",
            "Ça va durer environ 30 minutes.",
          ],
          questions: ["Tu es dans quelle énergie aujourd'hui ?", "C'est ok pour toi ?"],
          tips: ["Créer une connexion humaine avant de rentrer dans les questions", "Obtenir un OUI sur le déroulé"],
        },
        {
          order: 2, name: "Qualification — Niveau et situation actuelle", goal: "Comprendre le niveau, les habitudes sportives et les freins", duration_estimate_minutes: 10,
          key_phrases: ["C'est quoi ton niveau actuel ?", "Tu as déjà essayé ?", "Qu'est-ce qui t'a bloqué ?", "Tu as des contraintes physiques ?"],
          script_lines: [],
          questions: [
            "Qu'est-ce qui t'a amené à réserver cet appel ?",
            "C'est quoi ton niveau sportif actuel — tu cours déjà ou tu pars de zéro ?",
            "Tu as déjà essayé de te mettre au running ? Qu'est-ce qui s'est passé ?",
            "Combien de fois par semaine tu pourrais t'entraîner ?",
            "Tu as des contraintes physiques — genoux, dos, souffle ?",
            "C'est quoi ton objectif précis — finir un 5k, 10k, semi-marathon, maigrir, être en forme ?",
            "C'est pour quand cet objectif ?",
            "Qu'est-ce que ça représente pour toi de l'atteindre ?",
            "Qu'est-ce que tu as déjà essayé — applis, plans en ligne, coach ?",
            "Qui prend les décisions sur ce genre d'investissement dans ta vie ?",
          ],
          tips: ["Comprendre si l'objectif est un événement précis (course, date) ou un état (forme, poids)", "Identifier les tentatives passées — elles révèlent les vrais freins"],
        },
        {
          order: 3, name: "Jauger la motivation", goal: "Mesurer l'urgence et comprendre le 'pourquoi profond'", duration_estimate_minutes: 3,
          key_phrases: ["Sur une échelle de 0 à 10", "Pourquoi c'est important pour toi ?", "Qu'est-ce qui t'empêche de le faire seul ?"],
          script_lines: [],
          questions: [
            "Sur une échelle de 0 à 10, à combien tu évalues l'importance d'atteindre cet objectif ?",
            "Pourquoi tu m'as mis [ce score] et pas moins ?",
            "Qu'est-ce qui t'empêche d'y arriver seul avec un plan YouTube ou une appli ?",
            "Si tu n'atteins pas cet objectif dans 6 mois, tu te dis quoi ?",
          ],
          tips: ["Le 'pourquoi profond' est souvent émotionnel : santé, modèle pour les enfants, dépassement de soi, rupture", "Garder le 'pourquoi' pour la projection et le closing"],
        },
        {
          order: 4, name: "Projeter sur l'objectif", goal: "Cristalliser la vision du succès et l'émotion associée", duration_estimate_minutes: 3,
          key_phrases: ["Tu as passé la ligne d'arrivée", "Qu'est-ce que tu ressens ?", "Qu'est-ce que ça change dans ta vie ?"],
          script_lines: [],
          questions: [
            "Imagine qu'on est dans [X mois] et tu as atteint ton objectif — tu ressens quoi ?",
            "Tu franchis la ligne d'arrivée de ton premier [5k / 10k / semi] — qu'est-ce qui se passe en toi ?",
            "Qu'est-ce que ça changerait dans ta vie au quotidien ?",
            "C'est qui les personnes autour de toi qui compteraient le plus dans ce moment ?",
          ],
          tips: ["Laisser le prospect vivre l'émotion — ne pas l'interrompre", "Cette étape est la plus importante pour le closing émotionnel"],
        },
        {
          order: 5, name: "Récapitulatif et permission pitcher", goal: "Valider les enjeux et obtenir l'accord pour présenter l'accompagnement", duration_estimate_minutes: 2,
          key_phrases: ["Si j'ai bien compris", "C'est bien ça ?", "une décision dans un sens ou dans l'autre"],
          script_lines: [
            "Donc si j'ai bien compris, aujourd'hui tu es à [RECAP NIVEAU], ton objectif c'est [RECAP OBJECTIF] pour [DATE/RAISON], et ce qui t'a bloqué jusqu'ici c'est [RECAP FREIN].",
            "Moi je peux t'aider à y arriver.",
            "Avant que je te présente comment, j'ai besoin que tu t'engages à prendre une décision à la fin de cet appel — oui on avance ensemble, ou non tu continues seul.",
          ],
          questions: ["C'est bien ça ?", "Est-ce que tu me permets de te présenter mon accompagnement ?"],
          tips: ["Reformuler avec les mots du prospect", "Deux accords avant de pitcher"],
        },
        {
          order: 6, name: "Présentation de l'offre", goal: "Présenter le programme avec méthode, suivi et résultats attendus", duration_estimate_minutes: 5,
          key_phrases: ["[Nom du programme]", "[durée]", "Sur une échelle de 0 à 10, à combien tu es partant ?"],
          script_lines: [
            "[STORYTELLING] Pourquoi j'ai créé cet accompagnement : [votre histoire sportive, vos résultats, votre légitimité].",
            "Mon programme [NOM DU PROGRAMME] dure [DURÉE]. On va travailler sur : [plan d'entraînement personnalisé, progression, nutrition, mental, etc.].",
            "Pendant [DURÉE] tu auras : [lister les modalités : sessions, suivi hebdo, plan individualisé, disponibilité, etc.].",
            "À la fin, tu seras capable de [objectif concret] — et surtout tu auras les bases pour continuer seul.",
          ],
          questions: ["Ça te parle ?", "Des questions sur un point particulier ?", "Sur une échelle de 0 à 10, à combien tu es partant pour démarrer ?", "Qu'est-ce qui te manque pour aller à 9 ou 10 ?"],
          tips: ["Relier chaque élément du programme au problème spécifique du prospect", "Le score 0-10 révèle les objections — creuser directement"],
        },
        {
          order: 7, name: "Éligibilité", goal: "Retourner la dynamique — c'est vous qui choisissez", duration_estimate_minutes: 2,
          key_phrases: ["J'ai 3 critères", "Es-tu prêt à t'engager ?", "Tu m'as donné envie de t'accompagner"],
          script_lines: [
            "Pour que mon accompagnement soit efficace, j'ai 3 critères.",
            "Critère 1 : es-tu prêt à t'entraîner [X fois] par semaine même quand tu n'en as pas envie ?",
            "Critère 2 : es-tu prêt à faire confiance au processus même si la progression est lente au début ?",
            "Critère 3 : est-ce que cet objectif est vraiment important pour toi ?",
            "Tu m'as donné envie de t'accompagner. On y va.",
          ],
          questions: [],
          tips: ["Les 3 critères créent un engagement moral et responsabilisent le prospect", "L'inversion renverse le rapport de force"],
        },
        {
          order: 8, name: "Prix", goal: "Annoncer le prix clairement et ancrer la valeur", duration_estimate_minutes: 2,
          key_phrases: ["[votre prix]", "un investissement", "[découpage mensuel]"],
          script_lines: [
            "Pour accéder à [NOM DU PROGRAMME], c'est un investissement de [PRIX] pour [DURÉE].",
            "Ça comprend : [récapituler tous les livrables].",
          ],
          questions: [],
          tips: ["Annoncer sans hésitation", "Silence après le prix"],
        },
        {
          order: 9, name: "Closing", goal: "Obtenir le OUI et lancer l'accompagnement immédiatement", duration_estimate_minutes: 2,
          key_phrases: ["On part là-dessus ?", "Je t'envoie le lien", "Des zones d'ombre ?"],
          script_lines: [
            "→ SE TAIRE après la question. Le premier qui parle perd.",
            "Voilà comment ça se passe : je t'envoie le lien de paiement, on valide ensemble maintenant.",
            "Je t'envoie l'accès à [vos outils/plan de départ].",
            "On fixe notre premier point ensemble dans l'agenda.",
          ],
          questions: ["On part là-dessus ?", "Il y a encore des zones d'ombre ?"],
          tips: ["RÈGLE D'OR : silence après 'on part là-dessus ?'", "Enchaîner immédiatement sur les next steps après le OUI"],
        },
      ],
      objections: [
        { order: 1, label: "C'est trop cher", category: "price", trigger_phrases: ["c'est cher", "c'est trop cher", "le prix", "c'est beaucoup"], applicable_step_orders: [8, 9], responses: ["Je comprends. Mais dis-moi — combien tu as déjà dépensé en chaussures, abonnements salle, applis que tu n'as pas utilisés ?", "Ce n'est pas une dépense — c'est l'investissement qui va faire que cette fois ça marche vraiment.", "Si dans [X mois] tu as atteint ton objectif, tu trouveras encore ça trop cher ?"], key_reframe: "Comparer au coût de toutes les tentatives précédentes qui n'ont pas abouti" },
        { order: 2, label: "Je n'ai pas le temps", category: "timing", trigger_phrases: ["j'ai pas le temps", "je suis trop occupé", "avec le boulot", "avec les enfants"], applicable_step_orders: [6, 8, 9], responses: ["C'est quoi le minimum de temps par semaine que tu pourrais dégager ?", "Justement, un des avantages de l'accompagnement c'est que je construis le programme autour de tes contraintes — pas l'inverse.", "Les gens qui manquent de temps sont souvent ceux qui en ont le plus besoin — parce qu'ils négligent leur santé."], key_reframe: "L'accompagnement s'adapte aux contraintes — il faut moins de temps qu'on ne le croit" },
        { order: 3, label: "Je peux me faire un programme sur internet", category: "doubt", trigger_phrases: ["il y a des applis", "YouTube", "je vais trouver un plan gratuit", "Strava"], applicable_step_orders: [6, 8, 9], responses: ["Tu as probablement déjà essayé ça — qu'est-ce qui s'est passé ?", "La différence c'est la personnalisation et la responsabilité — un programme générique ne sait pas que tu as des genoux fragiles ou que tu as raté ta sortie mercredi.", "L'information ne manque pas — c'est le passage à l'action dans la durée qui manque."], key_reframe: "Le problème n'est pas l'accès au programme — c'est la constance et la personnalisation" },
        { order: 4, label: "Je vais y réfléchir", category: "stall", trigger_phrases: ["je vais y réfléchir", "laisse-moi le temps", "je reviens vers toi"], applicable_step_orders: [8, 9], responses: ["À quoi dois-tu réfléchir — il y a une information qui te manque ?", "Dans 3 mois, tu auras commencé seul ou tu seras toujours au même point ?", "Ta décision est liée aux informations que tu as — je suis là maintenant."], key_reframe: "La réflexion n'est jamais une question de temps — c'est une information manquante" },
        { order: 5, label: "J'ai peur de me blesser", category: "doubt", trigger_phrases: ["j'ai peur de me blesser", "mes genoux", "mon dos", "je suis fragile"], applicable_step_orders: [6, 7, 8, 9], responses: ["C'est justement l'argument le plus fort pour être accompagné plutôt que de faire ça seul.", "Un des piliers de mon accompagnement c'est la progression intelligente — on ne force jamais, on construit.", "Courir seul sans méthode, c'est là qu'on se blesse. Avec un programme adapté, le risque est minimal."], key_reframe: "L'accompagnement réduit le risque de blessure par rapport à courir seul sans méthode" },
        { order: 6, label: "Je dois en parler avec mon conjoint", category: "third_party", trigger_phrases: ["j'en parle à ma femme", "j'en parle à mon mari", "mon/ma conjoint(e)", "on décide ensemble"], applicable_step_orders: [8, 9], responses: ["Est-ce que tu penses qu'il/elle va te soutenir dans cet objectif ?", "Est-ce qu'il/elle sait à quel point cet objectif est important pour toi ?", "Est-ce que c'est une décision que tu peux prendre toi-même pour ton bien-être ?"], key_reframe: "Valoriser l'autonomie de décision pour son propre bien-être" },
      ],
    },
  },
];
