[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

[functions."*"]
  timeout = 120

[functions."analyze-call-bg"]
  timeout = 900
